version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api-dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=172.10.254.45,1433;Database=ECommerceApp;User Id=sa;Password=Asdf1234;TrustServerCertificate=True
    ports:
      - "7241:80"
    networks:
      - ecommerce-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web-dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ApiBaseUrl=http://api:80
    ports:
      - "7240:80"
    depends_on:
      - api
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  sqldata: 