version: '3.8'

services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - ecommerce-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sql;Database=ECommerceApp;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True
    ports:
      - "5241:80"
    depends_on:
      - sql
    networks:
      - ecommerce-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ApiBaseUrl=http://api
    ports:
      - "5240:80"
    depends_on:
      - api
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  sqldata: 