version: '3.8'

services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Asdf1234
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - ecommerce-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api-dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=172.10.254.45,1433;Database=ECommerceApp;User Id=sa;Password=Asdf1234;TrustServerCertificate=True
    volumes:
      - .:/src
      - /src/ECommerceApp.Api/bin/
      - /src/ECommerceApp.Api/obj/
    ports:
      - "7241:80"
    depends_on:
      - sql
    networks:
      - ecommerce-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web-dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ApiBaseUrl=http://localhost:7241
    volumes:
      - .:/src
      - /src/ECommerceApp.Web/bin/
      - /src/ECommerceApp.Web/obj/
    ports:
      - "7240:80"
    depends_on:
      - api
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  sqldata: 